### ISSUE TITLE
instance='http://localhost' not working

### ISSUE THREAD

**Issue by NetworkWebMasters** [bocchilorenzo/ntscraper#39]
I installed Nitter on ubuntu and http://localhost working perfectly, i can access and read twitter profile and tweets from localhost.

But instance='http://localhost'
like this not working.
scraper = Nitter(log_level=1, skip_instance_check=True)
bezos_tweets = scraper.get_tweets("JeffBezos", mode='user', instance='http://localhost')

Can you help me, How can i scrap tweets from http://localhost ?

**Comment by bocchilorenzo** [comment]
That's weird because I don't have any special code for localhost instances. The fact that your Nitter installation also tells you it's rate limited makes me think there is a problem with the configuration. Try checking out the comments at https://github.com/zedeus/nitter/issues/983 and see if they can help.
Also, when you had the max retries error you were passing the instance incorrectly. I'm not sure if you tried this already, but try launching the scraper like this:
`exportData = scraper.get_tweets(username, mode='user', since=sinceDate, until=untilDate, instance='http://localhost:8080')`

When passing the instance, you should omit the "/" at the end and if you use it locally you should also specify the port in the url.

**Comment by NetworkWebMasters** [comment]
I tried this https://github.com/zedeus/nitter/issues/983
I created new guest account tokens multiple times.

Actually Localhost instance works perfectly

The only issues is ntscraper wont detect it.

I also tried this
`exportData = scraper.get_tweets(username, mode='user', since=sinceDate, until=untilDate, instance='http://localhost:8080')`

**Comment by NetworkWebMasters** [comment]
Can you check this error?

CTraceback (most recent call last):
File "/home/ubuntu/Downloads/final.py", line 14, in
exportData = scraper.get_tweets(username, mode='user', since=sinceDate, until=untilDate, instance='http://localhost/')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/.local/lib/python3.11/site-packages/ntscraper/nitter.py", line 853, in get_tweets
return self._search(
^^^^^^^^^^^^^
File "/home/ubuntu/.local/lib/python3.11/site-packages/ntscraper/nitter.py", line 733, in _search
soup = self._get_page(endpoint, max_retries, no_empty_retries)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/.local/lib/python3.11/site-packages/ntscraper/nitter.py", line 278, in _get_page
sleep(2)

**Comment by bocchilorenzo** [comment]
Regarding the latest error, there was an issue with the endpoint creation that should now be fixed. Please try again with the latest version.

**Comment by NetworkWebMasters** [comment]
Thank you so much instance='http://localhost/' works perfectly now.

But there is one more issue

When i scrap tweets from 2023-12-10 to 2023-11-01

ntscraper only collect current December month's Retweets Quotes and Likes Counts

It wont collect November month's Retweets Quotes and Likes Counts
It only collect tweets counts of November month.

**Comment by bocchilorenzo** [comment]
The value in the "from" parameter should be the first date, while the one in the "to" attribute should be the last date. Try swapping them to see if it gets the tweets correctly.

**Comment by NetworkWebMasters** [comment]
I tried swapping them to see if it gets the tweets correctly.

but i found same issue.
