### ISSUE TITLE
ValueError: Could not fetch instances

### ISSUE THREAD

**Issue by JacobMatthew1121** [bocchilorenzo/ntscraper#40]
[Code.txt](https://github.com/bocchilorenzo/ntscraper/files/13544832/Code.txt)
Code uploaded.

**Comment by NetworkWebMasters** [comment]
Can you upload your complete code on github?

**Comment by JacobMatthew1121** [comment]
> Can you upload your complete code on github?

Uploaded.

**Comment by bocchilorenzo** [comment]
Hi,
that exception is raised when the scraper is unable to get the instances from the API. This usually happens when many requests are made towards it. For example, if you launch the script many times and the scraper gets initialized many times then there is a high chance that the API will rate limit you. Before this didn't happen because the instances were fetched from Nitter's wiki. I'll probably bring back the wiki fetching though because the API is also explicitly against scrapers. For now please try to initialize the scraper only once. You could do that using a jupyter notebook and putting the scraper initialization in its own block.

**Comment by 0xpr03** [comment]
Please note that the API is not for scraping because the instances are not for scraping!
