### ISSUE TITLE
Issue with Retweet Count Collection in ntscraper :- ntscraper wont collect retweets count after 8-9 days

### ISSUE THREAD

**Issue by NetworkWebMasters** [bocchilorenzo/ntscraper#46]
ntscraper wont collect retweets count after 8-9 days

sinceDate = 2023-12-01
untilDate = 2023-12-17

ntscraper only collects retweets count from 2023-12-08 to 2023-12-16 or 2023-12-09 to 2023-12-16

It wont collect retweets count from 2023-12-01 to 2023-12-08 or 2023-12-01 to 2023-12-09

**Comment by bocchilorenzo** [comment]
I think this could be related to #14 . I just tried through the website using the same links that i put in the comment to that issue and there are no retweets if a period is specified.

**Comment by bocchilorenzo** [comment]
Unfortunately this is a problem with Nitter. As you can see when you specify the dates on the website and go to https://nitter.net/SalaarTheSaga/search?f=tweets&q=&since=2023-12-01&until=2023-12-13&near=, it only shows the tweets and no retweets. If you add the filter to only show the retweets, as in https://nitter.net/SalaarTheSaga/search?f=tweets&q=&f-nativeretweets=on&since=2023-12-01&until=2023-12-13&near=, it still shows no retweets.

**Comment by NetworkWebMasters** [comment]
How can we extract data directly from an account instead of relying on a search-based approach?

**Comment by bocchilorenzo** [comment]
When filters are applied that is not possible. Data is extracted directly from main page of the account only when the username with no other filters is specified, otherwise the search mode for the account needs to be used. As far as I know, only retweets have this issue.

**Comment by NetworkWebMasters** [comment]
Ok got it and you're right only retweets have this issue.
